### ISSUE TITLE
build error according to the readme badge - on gh-pages branch - "NameError: name 'StandardError' is not defined"

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/editor-layer-index#694]
See https://github.com/osmlab/editor-layer-index#osm-editor-layer-index for badge
See https://travis-ci.org/osmlab/editor-layer-index/branches for branch list
See https://travis-ci.org/osmlab/editor-layer-index/builds/573027520 for specific failed build

```
Traceback (most recent call last):

  File "scripts/convert_xml.py", line 111, in <module>

    add_source(source)

  File "scripts/convert_xml.py", line 97, in add_source

    bounds.set('min-lon', coord_str(min(lons)))

  File "scripts/convert_xml.py", line 93, in coord_str

    return "{0:.6f}".format(coord)

TypeError: unsupported format string passed to list.__format__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "scripts/convert_xml.py", line 112, in <module>

    except StandardError:

NameError: name 'StandardError' is not defined

Makefile:16: recipe for target 'imagery.xml' failed

make: *** [imagery.xml] Error 1

The command "make" failed and exited with 2 during .
```

**Comment by grischard** [comment]
Thanks! Looks like a python 2 leftover.
