### ISSUE TITLE
Report file name with make check

### ISSUE THREAD

**Issue by pnorman** [osmlab/editor-layer-index#75]
I got this with `make check`. I knew which file it was, but it would be best to report it.

```
$ make check
Traceback (most recent call last):
  File "scripts/check.py", line 7, in <module>
    source = json.load(open(file))
  File "/usr/lib/python2.7/json/__init__.py", line 278, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 9 column 5 (char 271)
make: *** [check] Error 1
```

**Comment by grischard** [comment]
Fixed in https://github.com/osmlab/editor-layer-index/pull/406, so this can be closed
